version: '3.9'

services:
  web_xb:
    container_name: web_xb
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - .:/next/src/app
    environment:
    - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"